version: '3.8'

services:
  translation-api:
    build: .
    container_name: llm-translation-api
    ports:
      - "9000:9000"
      - "8001:8001"  # Metrics port
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_URL=redis://redis:6379/0
      - DB_URL=sqlite:///./data/translation_service.db
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - ollama
    restart: unless-stopped
    networks:
      - translation-network

  ollama:
    image: ollama/ollama:latest
    container_name: llm-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - translation-network
    # For GPU support, uncomment the following:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  redis:
    image: redis:7-alpine
    container_name: llm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - translation-network

  nginx:
    image: nginx:alpine
    container_name: llm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - translation-api
    restart: unless-stopped
    networks:
      - translation-network

volumes:
  ollama_data:
  redis_data:

networks:
  translation-network:
    driver: bridge
